# Generated by Django 4.1.7 on 2023-03-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
